language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/actionpack-5-0.gemfile
  - gemfiles/actionpack-5-1.gemfile
  - gemfiles/actionpack-5-2.gemfile
  - Gemfile

matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: Gemfile

cache: bundler

bundler_args: --jobs 3 --retry 3

before_install:
  - "rm -f ${BUNDLE_GEMFILE}.lock"