language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/actionpack_5_0.gemfile
  - gemfiles/actionpack_5_1.gemfile
  - gemfiles/actionpack_5_2.gemfile
  - Gemfile

matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: Gemfile

cache: bundler

bundler_args: --jobs 3 --retry 3

before_install:
  - "rm -f ${BUNDLE_GEMFILE}.lock"

jobs:
  include:
    - stage: rubocop
      rvm: 2.6.5
      gemfile: Gemfile
      script: 'bundle exec rubocop'